# -*- org -*-
#+TITLE: Dear Elizabeth Warren
#+COLUMNS: %12TODO %10WHO %3PRIORITY(PRI) %3HOURS(HRS){est+} %85ITEM
# #+INFOJS_OPT: view:showall toc:t ltoc:nil path:../org-info.js mouse:#B3F2E3
# Pandoc needs H:9; default is H:3.
# `^:nil' means raw underscores and carets are not interpreted to mean sub- and superscript.  (Use {} to force interpretation.)
#+OPTIONS: author:nil creator:t H:9 ^:{}
#+HTML_HEAD: <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=IBM+Plex+Mono:400,400i,600,600i|IBM+Plex+Sans:400,400i,600,600i|IBM+Plex+Serif:400,400i,600,600i">
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/org-mode.css" />

# Generates "up" and "home" links ("." is "current directory").  Can comment one out.
#+HTML_LINK_UP: .
#+HTML_LINK_HOME: /index.html

# Use ``#+ATTR_HTML: :class lower-alpha'' on line before list to use the following class.
# See https://emacs.stackexchange.com/a/18943/17421
# 
#+HTML_HEAD: <style type="text/css">
#+HTML_HEAD:  ol.lower-alpha { list-style-type: lower-alpha; }
#+HTML_HEAD: </style>

* Overview 

  My thoughts about how Elizabeth Warren needs to run her campaign.  [TODO: *NOT YET FINISHED*.]

  Yes, yes, I'm a clueless privileged white male, yada yada, but this here is my printing press, set up in the middle of
  the village green.
  
* Dear Elizabeth Warren,

  [TODO: graceful opening.]

  I just sent you some more money, so now I get to sound off.

  It's the -isms, not the "economic anxiety".  Racism, sexism, nativism.  Yes, econ anxiety is part of the mix, but: our
  economy is actually doing ok, and has been since the recovery* after '08.  Yes, people are afraid, but they're afraid
  for their children, not themselves.  Their fear leads to hoarding behavior along fault lines that coincide with race:
  More for the white people! Less for the undeserving poor!  The folks who put Trump in office are the "Bass Pro
  Bourgeoisie" (thanks @RobTaber):  economically comfortable, but they're still afraid.

  I know the recovery has been unbalanced and unfair.  Fewer people hold investments than before, the wealth gap
  is much worse, we have outrageous work-scheduling algorithms like "clopenings" and 15-minute chunks of scheduling with
  workers on-call but not paid to be, etc., etc.  That needs fixing, badly.  But I'm not sure those folks on the margins
  of our economic society are voting for Trump, are they?  Maybe they're staying home, and we need to get them to turn
  out, but the voters who put Trump in office (separate from the hardcore ones who proudly call themselves "deplorable")
  are the ones for whom this sort of suffering is less immediate: the ones who have more-or-less comfortable incomes.
  Joe the Plumber, for instance.

  I think you need to salt your message of economic fairness with an appeal to those
  comfortable-but-maybe-feeling-kinda-guilty Trump voters, the ones who wanted change but not the kind of chaos and
  hatred they got with Trump.  If they're kind-hearted and fair-minded (and I think many of them are, really), you need
  to appeal to that sense in them, and stop scaring them off by activating their old reflexes against "unfair
  preferential treatment" for people who don't look or sound like them.

  Black people aren't dumb.  They like Biden because they think he's a winner, and they think that because they think
  white people think that.  The focus is on the white people (still) and that's where the victory is.  (Although, ya
  know... once you get in office, don't /forget/ your (implied) promises to black people.  We really do need the
  problems we've created by being racists.)
  
** Racism (and sexism, for that matter)

   Stop saying what wonderful things you're going to do for black people to right past wrongs.  I support it, but you're
   going to scare the white folks.  Instead, /enlist/ the white folks.  Black folks are going to be smart enough when
   you speak to the white folks about fairness.

   Lots of white folks have a strong sense of fair play.  Speak to that.  Who wants to win by cheating?  Who wants to be
   a part of this terrible system we have now?  Why have artificial barriers to equal opportunity for all?  Talk less
   about what /you're/ going to do, and more about what /we're/ going to do.  We're going to dismantle things.  We're
   going to give up a little power (we can spare it, and we've done it in the past).

   The benefits to the country will be enormous if we fully utilize everybody's capability.  If we stopped holding women
   and minorities back in STEM, for instance, imagine how much easier it would be to "find good help".

   If we had more female corporate leadership and less testerone, imagine how much more cooperative corporate culture
   would be.  (I mean, at the workplace, not in terms of competition between corporations.)  Imagine how much more
   productivity we'd get out of people who had room in their lives for childcare and eldercare.  Imagine the benefits of
   quality public daycare.  /Message this./  Less about what /you're/ going to do and more about what /we're/ going to
   do, in electing you.  (I know, you already say "In a Warren administration...", so maybe I'm misinterpreting, but it
   sounds like "what /I'm/ going to do is...".)

   If we stopped wasting our resources on racist policing, imagine how much more effective we could be in policing
   actual crime, both because our resources would be better directed and the citizenry would be more amenable/helpful.
   Message that.

   +How do we do that?  Put a stop to toxic masculinity in elementary school.  I know there are tons of teachers who
   already want to do that; maybe we should hire (and retain) more of them.+

   Imagine how much electing a woman president, just by itself, would change the tone of the system (w.r.t. women).
   That's an "us" thing, not a "you" thing.  (Um, I'm not sure how you message that.)

*** Past accomplishments by the folks in power at the time

**** Civil War and 13th, 14th, and 15th Amendments

     Not much of an "accomplishment", but white people did go to war over slavery, because it was wrong, plain and
     simple.
     
**** 19th Amendment

     Men gave women the right to vote.  [Except... I just listened to a podcast episode of /Talking Politics/ ([[https://www.talkingpoliticspodcast.com/blog/2020/212-the-15th-and-the-19th][Episode
     212]]) in which the 19th amendment passed because of appeals to racism and promises to white men that we wouldn't
     allow black /women/ to vote, so... <shrug/> I dunno... /kinda???/]

**** Civil Rights

     White people were the deciding factor.  Black people couldn't do it alone.

** Nuclear power

   The U.S. nuclear industry is
   in bad shape, I hear, so fix it; don't pitch it out.  Maybe you weren't serious when you said "we're not going to
   build nuclear power in this country" (or whatever it was you said), but this is a tribal identification you're
   aligning yourself with, not good policy.  Break that stereotype, let the anti-nuclear left howl and springboard off
   of that, more to the center.

** Coattails

   You need to think about 'em.  You can't just win by yourself; you need to sweep a bunch of folks into Congress with
   you (state/local folks would be nice, too).

* Notes

** <2019-12-31 Tue>

*** Resurface old political ad

    Ok, so you did that today (or thereabouts) and it's good; it's everything I'm asking for above (or most of it).
    
