# -*- org -*-
#+TITLE: Notes on Linux Mint 19.1 on a Lenovo T440s
#+COLUMNS: %12TODO %10WHO %3PRIORITY(PRI) %3HOURS(HRS){est+} %85ITEM
# #+INFOJS_OPT: view:showall toc:t ltoc:nil path:../org-info.js mouse:#B3F2E3
# Pandoc needs H:9; default is H:3.
# `^:nil' means raw underscores and carets are not interpreted to mean sub- and superscript.  (Use {} to force interpretation.)
#+OPTIONS: author:nil creator:t H:9 ^:{}
#+HTML_HEAD: <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=IBM+Plex+Mono:400,400i,600,600i|IBM+Plex+Sans:400,400i,600,600i|IBM+Plex+Serif:400,400i,600,600i">
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/org-mode.css" />

# Generates "up" and "home" links ("." is "current directory").  Can comment one out.
#+HTML_LINK_UP: .
#+HTML_LINK_HOME: /index.html

# Use ``#+ATTR_HTML: :class lower-alpha'' on line before list to use the following class.
# See https://emacs.stackexchange.com/a/18943/17421
# 
#+HTML_HEAD: <style type="text/css">
#+HTML_HEAD:  ol.lower-alpha { list-style-type: lower-alpha; }
#+HTML_HEAD: </style>

* Overview

  I installed Linux Mint 19.1 on my old corporate Lenovo Thinkpad T440s (since the company didn't
  want it any more and didn't want to pay recycling costs).  These are /some/ of the things I had to
  figure out.

* Disable Trackpoint

  Hitting the trackpoint while I type can do dumb things with the mouse, so I wanted to disable it.

  #+BEGIN_EXAMPLE
    Charon$ xinput -list | less
    ⎡ Virtual core pointer                          id=2    [master pointer  (3)]
    ⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
    ⎜   ↳ SynPS/2 Synaptics TouchPad                id=13   [slave  pointer  (2)]
    ⎜   ↳ TPPS/2 IBM TrackPoint                     id=14   [slave  pointer  (2)]
  #+END_EXAMPLE

  #+BEGIN_EXAMPLE
    Charon$ xinput list-props 14 | less
    Device 'TPPS/2 IBM TrackPoint':
            Device Enabled (143):   1
  #+END_EXAMPLE

  Note: I haven't tried to change this yet.

* DONE Install AWS CLI -- "ModuleNotFoundError -- setuptools"
  CLOSED: [2019-03-07 Thu 22:15]

  - CLOSING NOTE [2019-03-07 Thu 22:15] \\
    Solution: =pip3 install setuptools= (assuming you're using =pip3= to install the awscli).

  #+BEGIN_EXAMPLE
        ModuleNotFoundError: No module named 'setuptools'
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vx9id3mw/PyYAML/
  #+END_EXAMPLE
  
* Use TLP to set battery charge threshholds

  So you don't constantly charge your battery to 100%, which hurts its life.

  I haven't quite figured out if this thing is working properly, since the "power manager" applet on
  the task bar reports that the laptop is always charging.
  
* Pandora: Use Pithos

  The Pandora web app doesn't work so well on Linux, but there is another app that you can use:
  Pithos seems to work.
  
* Making Alt-ESC send windows to the background

  I love getting rid of a window in Windows with Alt-ESC to send it to the background.  To do this
  in Mint (19.1, Cinnamon):

  - Run the "keyboard" preferences applet (hit the "windows" key and type "keyboard" to search for
    it).

  - Select "Shortcuts".

  - Select "Windows" in the "Categories" pane (for shortcuts pertaining to windows).

  - Select "Lower window" in the right pane.

  - Enter your desired shortcut sequence (Alt-ESC).

* Transpose Left-Control and Caps-Lock

  Probably similar to the above for Alt-ESC.
  
* Brave browser

  Stupid Brave repository keeps going offline or whatever.  Brave people can't seem to manage it
  properly and I get "unable to update"-type messages from Mint Update or Aptitude or whatever.

  So... repository management.  See below ([[#software-repository-management][Software package repository management]]).

** Installation
   
   Brave install commands ([2021-03-27 Sat]):

   #+BEGIN_EXAMPLE
     sudo apt install apt-transport-https curl gnupg

     curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

     echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list

     sudo apt update

     sudo apt install brave-browser
   #+END_EXAMPLE 

** Shortcut/applet on task bar

   Just kind of magically showed up after installation and logout/login, /BUT/... maybe right-click
   on app icon (in system menu, where installation puts it) and selecting "Add to Panel" had
   something to do with it.
   
* Software package repository management
  :PROPERTIES:
  :CUSTOM_ID: software-repository-management
  :END:

  Use one of:

  - Mint Updates (system software)
  - Synaptic (GUI)
  - aptitude (cmd-line)

** Packages installed (PPAs, additional repos)

   - ichthyo/zeug :: For Electric Sheep.  Upgrades apparently require building from scratch?
   - Brave :: There is a repo, under Mint Update | Edit | Software Sources | Additional Repos.

              
