# -*- org -*-
#+TITLE: Notes on Linux Mint 19.1 on a Lenovo T440s
#+COLUMNS: %12TODO %10WHO %3PRIORITY(PRI) %3HOURS(HRS){est+} %85ITEM
# #+INFOJS_OPT: view:showall toc:t ltoc:nil path:../org-info.js mouse:#B3F2E3
# Pandoc needs H:9; default is H:3.
# `^:nil' means raw underscores and carets are not interpreted to mean sub- and superscript.  (Use {} to force interpretation.)
#+OPTIONS: author:nil creator:t H:9 ^:{}
#+HTML_HEAD: <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=IBM+Plex+Mono:400,400i,600,600i|IBM+Plex+Sans:400,400i,600,600i|IBM+Plex+Serif:400,400i,600,600i">
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/org-mode.css" />

# Generates "up" and "home" links ("." is "current directory").  Can comment one out.
#+HTML_LINK_UP: .
#+HTML_LINK_HOME: /index.html

# Use ``#+ATTR_HTML: :class lower-alpha'' on line before list to use the following class.
# See https://emacs.stackexchange.com/a/18943/17421
# 
#+HTML_HEAD: <style type="text/css">
#+HTML_HEAD:  ol.lower-alpha { list-style-type: lower-alpha; }
#+HTML_HEAD: </style>

* Overview

  I installed Linux Mint 19.1 on my old corporate Lenovo Thinkpad T440s (since the company didn't
  want it any more and didn't want to pay recycling costs).  These are /some/ of the things I had to
  figure out.

* Disable Trackpoint

  Hitting the trackpoint while I type can do dumb things with the mouse, so I wanted to disable it.

  #+BEGIN_EXAMPLE
    Charon$ xinput -list | less
    ⎡ Virtual core pointer                          id=2    [master pointer  (3)]
    ⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
    ⎜   ↳ SynPS/2 Synaptics TouchPad                id=13   [slave  pointer  (2)]
    ⎜   ↳ TPPS/2 IBM TrackPoint                     id=14   [slave  pointer  (2)]
  #+END_EXAMPLE

  #+BEGIN_EXAMPLE
    Charon$ xinput list-props 14 | less
    Device 'TPPS/2 IBM TrackPoint':
            Device Enabled (143):   1
  #+END_EXAMPLE

  Note: I haven't tried to change this yet.

* DONE Install AWS CLI -- "ModuleNotFoundError -- setuptools"
  CLOSED: [2019-03-07 Thu 22:15]

  - CLOSING NOTE [2019-03-07 Thu 22:15] \\
    Solution: =pip3 install setuptools= (assuming you're using =pip3= to install the awscli).

  #+BEGIN_EXAMPLE
        ModuleNotFoundError: No module named 'setuptools'
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vx9id3mw/PyYAML/
  #+END_EXAMPLE
  
* Use TLP to set battery charge threshholds

  So you don't constantly charge your battery to 100%, which hurts its life.

  I haven't quite figured out if this thing is working properly, since the "power manager" applet on
  the task bar reports that the laptop is always charging.
  
* Pandora: Use Pithos

  The Pandora web app doesn't work so well on Linux, but there is another app that you can use:
  Pithos seems to work.
  
* Making Alt-ESC send windows to the background

  I love getting rid of a window in Windows with Alt-ESC to send it to the background.  To do this
  in Mint (19.1, Cinnamon):

  - Run the "keyboard" preferences applet (hit the "windows" key and type "keyboard" to search for
    it).

  - Select "Shortcuts".

  - Select "Windows" in the "Categories" pane (for shortcuts pertaining to windows).

  - Select "Lower window" in the right pane.

  - Enter your desired shortcut sequence (Alt-ESC).

* Transpose Left-Control and Caps-Lock

  Probably similar to the above for Alt-ESC.
  

    

  
